#!/bin/bash

function CreateNodeFile {
  CREATENODEFILE_BODY=$(eval echo $1)
  CREATENODEFILE_OUT=$(eval echo $2)

  # The following replacements maintain the punctuation
  # replace "$" with "\\\$"
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\$/\\\\\\\$}
  # replace "`" with "\\\`"
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\`/\\\\\\\`}
  # replace "'" with "\\\'"
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\'/\\\\\\\'}
  # replace '"' with '\\"'
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\"/\\\\\\\"}
  # replace "\\n" with "\\\\n"
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\\n/\\\\n}

  # replace end of lines with \n
  CREATENODEFILE_BODY=$(eval echo \"$CREATENODEFILE_BODY\" | sed 's/$/DRONE_WRITE_FILE_EOL/')

  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\\\$/\$}
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\\\`/\`}
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\\\'/\'}
  CREATENODEFILE_BODY=${CREATENODEFILE_BODY//\\\"/\"}
  echo 'module.exports = ' \
    $(echo $CREATENODEFILE_BODY \
      | sed 's/DRONE_WRITE_FILE_EOL/\\n/g' \
      | sed 's/\\n$//') \
    > $CREATENODEFILE_OUT
}

# Strange syntax preserves spaces
CreateNodeFile "\${PLUGIN_IF}" "/node/plugin-if.js"
CreateNodeFile "\${PLUGIN_BODY}" "/node/plugin-body.js"

# Remove if exists, ignore errors
rm $PLUGIN_OUT || true
# Create directories if not exists, ignore errors
mkdir -p $(dirname $PLUGIN_OUT) || true

node /node/run.js > $PLUGIN_OUT
