#!/bin/bash

function CreateNodeFile {
  body=$(eval echo "$1")
  scriptFile=$(eval echo "$2")

  # The following replacements maintain the punctuation
  # replace "`" with "\\\`"
  body=${body//\`/\\\`}
  # replace "'" with "\\\'"
  body=${body//\'/\\\'}
  # replace "\\n" with "\\\\n"
  body=${body//\\n/\\\\n}

  # replace end of lines with \n
  body=$(eval echo \"$body\" | sed 's/$/DRONE_WRITE_FILE_EOL/')

  body=${body//\\\`/\`}
  body=${body//\\\'/\'}
  echo 'module.exports = ' \
    "$(echo "$body" \
      | sed 's/DRONE_WRITE_FILE_EOL/\\n/g' \
      | sed 's/\\n$//')" \
    > "$scriptFile"
}

# Strange syntax preserves spaces
CreateNodeFile "\${PLUGIN_IF}" "/node/plugin-if.js"
CreateNodeFile "\${PLUGIN_BODY}" "/node/plugin-body.js"

# Remove if exists, ignore errors
rm "$PLUGIN_OUT" 2> /dev/null
# Create directories if not exists, ignore errors
mkdir -p "$(dirname "$PLUGIN_OUT")"

node /node/run.js > "$PLUGIN_OUT"
if [ -e "$PLUGIN_OUT" ]; then
  if [ -s "$PLUGIN_OUT" ]; then
    echo -e "\e[92mCreated file: \e[0m$PLUGIN_OUT"
  else
    rm "$PLUGIN_OUT"
    echo -e "\e[93mNo file created.\e[0m"
  fi
fi
